/*
 * Pipeline Magnetic Field Searcher
 */
package ru.gss.pmfsearcher.calculation;

import javax.swing.SpinnerNumberModel;
import javax.swing.text.DefaultFormatterFactory;
import org.jdesktop.application.Action;
import ru.gss.pmfsearcher.commons.DlgDirEdit;
import ru.gss.pmfsearcher.commons.NoLocaleNumberFormatter;
import ru.gss.pmfsearcher.data.Parameter;

/**
 * Dialog for edit of model parameters.
 * @version 1.1.0 21.01.2021
 * @author Sergey Guskov
 */
public class DlgParameterEdit extends DlgDirEdit <Parameter> {

    /**
     * Constructor.
     */
    public DlgParameterEdit() {
        super();
        initComponents();
        jftfDiameter.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfThickness.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(4)));
        jftfDepth.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfValueBegin.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfValueStep.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jspValueCount.setModel(new SpinnerNumberModel(101, 10, 10000, 100));
    }

    /**
     * Setter editing object.
     * @param aTempObj editing object
     */
    @Override
    public void setTempObj(final Parameter aTempObj) {
        putTempObj(aTempObj);
        jftfDiameter.setValue(getTempObj().getDiameter());
        jftfThickness.setValue(getTempObj().getThickness());
        jftfDepth.setValue(getTempObj().getDepth());
        jftfValueBegin.setValue(getTempObj().getCoordBegin());
        jftfValueStep.setValue(getTempObj().getCoordStep());
        jspValueCount.setValue(getTempObj().getCoordCount());     
    }

    /**
     * Init new object.
     * @return new object
     */
    @Override
    public Parameter createTempObj() {
        return new Parameter();
    }

    /**
     * Action for Cancel button.
     */
    @Action
    public void acCancel() {
        setChangeObj(false);
    }

    /**
     * Action for OK button.
     */
    @Action
    public void acOk() {
        if (checkFormattedTextFieldNullNoSupposed(jftfDiameter, 0.1, 1.5)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfThickness, 1e-3, 0.1)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfDepth, 0.5, 50.0)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfValueBegin, -1e5, 1e5)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfValueStep, 0.1, 1e3)) {
            return;
        }
        getTempObj().setDiameter(getDoubleFromFormattedTextField(jftfDiameter));
        getTempObj().setThickness(getDoubleFromFormattedTextField(jftfThickness));
        getTempObj().setDepth(getDoubleFromFormattedTextField(jftfDepth));
        getTempObj().setCoordBegin(getDoubleFromFormattedTextField(jftfValueBegin));
        getTempObj().setCoordStep(getDoubleFromFormattedTextField(jftfValueStep));
        getTempObj().setCoordCount((Integer) jspValueCount.getValue());
        setChangeObj(true);
    }

    //CHECKSTYLE:OFF
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbDiameter = new javax.swing.JLabel();
        jftfDiameter = new javax.swing.JFormattedTextField();
        jlbThickness = new javax.swing.JLabel();
        jftfThickness = new javax.swing.JFormattedTextField();
        jlbDepth = new javax.swing.JLabel();
        jftfDepth = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbValueBegin = new javax.swing.JLabel();
        jftfValueBegin = new javax.swing.JFormattedTextField();
        jlbValueStep = new javax.swing.JLabel();
        jftfValueStep = new javax.swing.JFormattedTextField();
        jlbValueCount = new javax.swing.JLabel();
        jspValueCount = new javax.swing.JSpinner();
        jbtnOk = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ru.gss.pmfsearcher.PMFSearcherApp.class).getContext().getResourceMap(DlgParameterEdit.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jlbDiameter.setText(resourceMap.getString("jlbDiameter.text")); // NOI18N
        jlbDiameter.setName("jlbDiameter"); // NOI18N

        jftfDiameter.setName("jftfDiameter"); // NOI18N

        jlbThickness.setText(resourceMap.getString("jlbThickness.text")); // NOI18N
        jlbThickness.setName("jlbThickness"); // NOI18N

        jftfThickness.setName("jftfThickness"); // NOI18N

        jlbDepth.setText(resourceMap.getString("jlbDepth.text")); // NOI18N
        jlbDepth.setName("jlbDepth"); // NOI18N

        jftfDepth.setName("jftfDepth"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbThickness)
                    .addComponent(jlbDepth)
                    .addComponent(jlbDiameter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jftfDiameter)
                    .addComponent(jftfThickness)
                    .addComponent(jftfDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDiameter)
                    .addComponent(jftfDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbThickness)
                    .addComponent(jftfThickness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDepth)
                    .addComponent(jftfDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jlbValueBegin.setText(resourceMap.getString("jlbValueBegin.text")); // NOI18N
        jlbValueBegin.setName("jlbValueBegin"); // NOI18N

        jftfValueBegin.setName("jftfValueBegin"); // NOI18N

        jlbValueStep.setText(resourceMap.getString("jlbValueStep.text")); // NOI18N
        jlbValueStep.setName("jlbValueStep"); // NOI18N

        jftfValueStep.setName("jftfValueStep"); // NOI18N

        jlbValueCount.setText(resourceMap.getString("jlbValueCount.text")); // NOI18N
        jlbValueCount.setName("jlbValueCount"); // NOI18N

        jspValueCount.setName("jspValueCount"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbValueBegin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addComponent(jlbValueStep)
                    .addComponent(jlbValueCount))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jspValueCount)
                    .addComponent(jftfValueStep)
                    .addComponent(jftfValueBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValueBegin)
                    .addComponent(jftfValueBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValueStep)
                    .addComponent(jftfValueStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValueCount)
                    .addComponent(jspValueCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ru.gss.pmfsearcher.PMFSearcherApp.class).getContext().getActionMap(DlgParameterEdit.class, this);
        jbtnOk.setAction(actionMap.get("acOk")); // NOI18N
        jbtnOk.setName("jbtnOk"); // NOI18N

        jbtnCancel.setAction(actionMap.get("acCancel")); // NOI18N
        jbtnCancel.setName("jbtnCancel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnOk)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JFormattedTextField jftfDepth;
    private javax.swing.JFormattedTextField jftfDiameter;
    private javax.swing.JFormattedTextField jftfThickness;
    private javax.swing.JFormattedTextField jftfValueBegin;
    private javax.swing.JFormattedTextField jftfValueStep;
    private javax.swing.JLabel jlbDepth;
    private javax.swing.JLabel jlbDiameter;
    private javax.swing.JLabel jlbThickness;
    private javax.swing.JLabel jlbValueBegin;
    private javax.swing.JLabel jlbValueCount;
    private javax.swing.JLabel jlbValueStep;
    private javax.swing.JSpinner jspValueCount;
    // End of variables declaration//GEN-END:variables
    //CHECKSTYLE:ON
}
