/*
 * Pipeline Magnetic Field Searcher
 */
package ru.gss.pmfsearcher.calculation;

import javax.swing.text.DefaultFormatterFactory;
import org.jdesktop.application.Action;
import ru.gss.pmfsearcher.commons.DlgDirEdit;
import ru.gss.pmfsearcher.commons.NoLocaleNumberFormatter;
import ru.gss.pmfsearcher.data.Source;

/**
 * Dialog for edit of source.
 * @version 1.1.0 21.01.2021
 * @author Sergey Guskov
 */
public class DlgSourceEdit extends DlgDirEdit < Source > {

    /**
     * Constructor.
     */
    public DlgSourceEdit() {
        super();
        initComponents();
        jftfCoordLinear.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfCoordAngular.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfMagnetizationX.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfMagnetizationY.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfMagnetizationZ.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfLengthLinear.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfLengthAngular.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfStepLinear.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfStepAngular.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
    }

    /**
     * Setter editing object.
     * @param aTempObj editing object
     */
    @Override
    public void setTempObj(final Source aTempObj) {
        putTempObj(aTempObj);
        jftfCoordLinear.setValue(getTempObj().getCoordLinear());
        jftfCoordAngular.setValue(getTempObj().getCoordAngular());
        jftfMagnetizationX.setValue(getTempObj().getMagnetization().getX());
        jftfMagnetizationY.setValue(getTempObj().getMagnetization().getY());
        jftfMagnetizationZ.setValue(getTempObj().getMagnetization().getZ());
        jftfLengthLinear.setValue(getTempObj().getLengthLinear());
        jftfLengthAngular.setValue(getTempObj().getLengthAngular());
        jftfStepLinear.setValue(getTempObj().getStepLinear());
        jftfStepAngular.setValue(getTempObj().getStepAngular());
        getRootPane().setDefaultButton(jbtnOk);
    }

    /**
     * Init new object.
     * @return new object
     */
    @Override
    public Source createTempObj() {
        return new Source();
    }

    /**
     * Action for Cancel button.
     */
    @Action
    public void acCancel() {
        setChangeObj(false);
    }

    /**
     * Action for OK button.
     */
    @Action
    public void acOk() {
        if (checkFormattedTextFieldNullNoSupposed(jftfCoordLinear, -1e5, 1e5)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfCoordAngular, -360.0, 360.0)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfLengthLinear, 0.0, 1e4)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfLengthAngular, 0.0, 360.0)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfStepLinear, 0.0, 10.0)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfStepAngular, 0.0, 360.0)) {
            return;
        }
         if (checkFormattedTextFieldNullNoSupposed(jftfMagnetizationX, -1e8, 1e8)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfMagnetizationY, -1e8, 1e8)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfMagnetizationZ, -1e8, 1e8)) {
            return;
        }
        getTempObj().setCoordLinear(getDoubleFromFormattedTextField(jftfCoordLinear));
        getTempObj().setCoordAngular(getDoubleFromFormattedTextField(jftfCoordAngular));
        getTempObj().setLengthLinear(getDoubleFromFormattedTextField(jftfLengthLinear));
        getTempObj().setLengthAngular(getDoubleFromFormattedTextField(jftfLengthAngular));
        getTempObj().setStepLinear(getDoubleFromFormattedTextField(jftfStepLinear));
        getTempObj().setStepAngular(getDoubleFromFormattedTextField(jftfStepAngular));
        getTempObj().getMagnetization().setX(getDoubleFromFormattedTextField(jftfMagnetizationX));
        getTempObj().getMagnetization().setY(getDoubleFromFormattedTextField(jftfMagnetizationY));
        getTempObj().getMagnetization().setZ(getDoubleFromFormattedTextField(jftfMagnetizationZ));
        setChangeObj(true);
    }

    //CHECKSTYLE:OFF
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnOk = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlbCoordLinear = new javax.swing.JLabel();
        jftfCoordLinear = new javax.swing.JFormattedTextField();
        jlbCoordAngular = new javax.swing.JLabel();
        jftfCoordAngular = new javax.swing.JFormattedTextField();
        jlbLengthLinear = new javax.swing.JLabel();
        jftfLengthLinear = new javax.swing.JFormattedTextField();
        jlbLengthAngular = new javax.swing.JLabel();
        jftfLengthAngular = new javax.swing.JFormattedTextField();
        jlbStepLinear = new javax.swing.JLabel();
        jftfStepLinear = new javax.swing.JFormattedTextField();
        jlbStepAngular = new javax.swing.JLabel();
        jftfStepAngular = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbMagnetizationX = new javax.swing.JLabel();
        jftfMagnetizationX = new javax.swing.JFormattedTextField();
        jlbMagnetizationY = new javax.swing.JLabel();
        jftfMagnetizationY = new javax.swing.JFormattedTextField();
        jlbMagnetizationZ = new javax.swing.JLabel();
        jftfMagnetizationZ = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ru.gss.pmfsearcher.PMFSearcherApp.class).getContext().getResourceMap(DlgSourceEdit.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ru.gss.pmfsearcher.PMFSearcherApp.class).getContext().getActionMap(DlgSourceEdit.class, this);
        jbtnOk.setAction(actionMap.get("acOk")); // NOI18N
        jbtnOk.setName("jbtnOk"); // NOI18N

        jbtnCancel.setAction(actionMap.get("acCancel")); // NOI18N
        jbtnCancel.setName("jbtnCancel"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jlbCoordLinear.setText(resourceMap.getString("jlbCoordLinear.text")); // NOI18N
        jlbCoordLinear.setName("jlbCoordLinear"); // NOI18N

        jftfCoordLinear.setName("jftfCoordLinear"); // NOI18N

        jlbCoordAngular.setText(resourceMap.getString("jlbCoordAngular.text")); // NOI18N
        jlbCoordAngular.setName("jlbCoordAngular"); // NOI18N

        jftfCoordAngular.setName("jftfCoordAngular"); // NOI18N

        jlbLengthLinear.setText(resourceMap.getString("jlbLengthLinear.text")); // NOI18N
        jlbLengthLinear.setName("jlbLengthLinear"); // NOI18N

        jftfLengthLinear.setName("jftfLengthLinear"); // NOI18N

        jlbLengthAngular.setText(resourceMap.getString("jlbLengthAngular.text")); // NOI18N
        jlbLengthAngular.setName("jlbLengthAngular"); // NOI18N

        jftfLengthAngular.setName("jftfLengthAngular"); // NOI18N

        jlbStepLinear.setText(resourceMap.getString("jlbStepLinear.text")); // NOI18N
        jlbStepLinear.setName("jlbStepLinear"); // NOI18N

        jftfStepLinear.setName("jftfStepLinear"); // NOI18N

        jlbStepAngular.setText(resourceMap.getString("jlbStepAngular.text")); // NOI18N
        jlbStepAngular.setName("jlbStepAngular"); // NOI18N

        jftfStepAngular.setName("jftfStepAngular"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCoordAngular)
                    .addComponent(jlbCoordLinear)
                    .addComponent(jlbLengthLinear)
                    .addComponent(jlbLengthAngular)
                    .addComponent(jlbStepLinear)
                    .addComponent(jlbStepAngular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftfStepAngular)
                    .addComponent(jftfStepLinear)
                    .addComponent(jftfLengthAngular)
                    .addComponent(jftfLengthLinear)
                    .addComponent(jftfCoordLinear)
                    .addComponent(jftfCoordAngular, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCoordLinear)
                    .addComponent(jftfCoordLinear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCoordAngular)
                    .addComponent(jftfCoordAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfLengthLinear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbLengthLinear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfLengthAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbLengthAngular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStepLinear)
                    .addComponent(jftfStepLinear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStepAngular)
                    .addComponent(jftfStepAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jlbMagnetizationX.setText(resourceMap.getString("jlbMagnetizationX.text")); // NOI18N
        jlbMagnetizationX.setName("jlbMagnetizationX"); // NOI18N

        jftfMagnetizationX.setName("jftfMagnetizationX"); // NOI18N

        jlbMagnetizationY.setText(resourceMap.getString("jlbMagnetizationY.text")); // NOI18N
        jlbMagnetizationY.setName("jlbMagnetizationY"); // NOI18N

        jftfMagnetizationY.setName("jftfMagnetizationY"); // NOI18N

        jlbMagnetizationZ.setText(resourceMap.getString("jlbMagnetizationZ.text")); // NOI18N
        jlbMagnetizationZ.setName("jlbMagnetizationZ"); // NOI18N

        jftfMagnetizationZ.setName("jftfMagnetizationZ"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMagnetizationX)
                    .addComponent(jlbMagnetizationY)
                    .addComponent(jlbMagnetizationZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftfMagnetizationZ)
                    .addComponent(jftfMagnetizationY)
                    .addComponent(jftfMagnetizationX, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfMagnetizationX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMagnetizationX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfMagnetizationY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMagnetizationY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfMagnetizationZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMagnetizationZ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOk)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JFormattedTextField jftfCoordAngular;
    private javax.swing.JFormattedTextField jftfCoordLinear;
    private javax.swing.JFormattedTextField jftfLengthAngular;
    private javax.swing.JFormattedTextField jftfLengthLinear;
    private javax.swing.JFormattedTextField jftfMagnetizationX;
    private javax.swing.JFormattedTextField jftfMagnetizationY;
    private javax.swing.JFormattedTextField jftfMagnetizationZ;
    private javax.swing.JFormattedTextField jftfStepAngular;
    private javax.swing.JFormattedTextField jftfStepLinear;
    private javax.swing.JLabel jlbCoordAngular;
    private javax.swing.JLabel jlbCoordLinear;
    private javax.swing.JLabel jlbLengthAngular;
    private javax.swing.JLabel jlbLengthLinear;
    private javax.swing.JLabel jlbMagnetizationX;
    private javax.swing.JLabel jlbMagnetizationY;
    private javax.swing.JLabel jlbMagnetizationZ;
    private javax.swing.JLabel jlbStepAngular;
    private javax.swing.JLabel jlbStepLinear;
    // End of variables declaration//GEN-END:variables
    //CHECKSTYLE:ON
}
